FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudops-worker ./cmd/worker

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /app/cloudops-worker /app/cloudops-worker
EXPOSE 9091
ENTRYPOINT ["/app/cloudops-worker"]
