FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o cloudops-server .

FROM gcr.io/distroless/static-debian12
WORKDIR /app
COPY --from=builder /app/cloudops-server /app/cloudops-server
EXPOSE 8080
ENTRYPOINT ["/app/cloudops-server"]
