apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudops-worker
  namespace: cloudops
  labels:
    app.kubernetes.io/name: cloudops-worker
    app.kubernetes.io/part-of: cloudops-monitor
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudops-worker
  namespaceSelector:
    matchNames:
      - cloudops
  endpoints:
    - port: metrics
      path: /metrics
      interval: 15s
